name: Create a comment on new issues

on:
 issues:
   types: [opened]

jobs:
  comment-with-action:
      runs-on: ubunut-latest
      steps: 
         - name: "dump github context"
           run: echo '${{toJSON(github.event)}}' | jq
